% Produced by CVXGEN, 2022-06-01 01:00:28 -0400.
% CVXGEN is Copyright (C) 2006-2017 Jacob Mattingley, jem@cvxgen.com.
% The code in this file is Copyright (C) 2006-2017 Jacob Mattingley.
% CVXGEN, or solvers produced by CVXGEN, cannot be used for commercial
% applications without prior written permission from Jacob Mattingley.

% Filename: cvxsolve.m.
% Description: Solution file, via cvx, for use with sample.m.
function [vars, status] = cvxsolve(params, settings)
H = params.H;
f = params.f;
lb = params.lb;
ub = params.ub;
cvx_begin
  % Caution: automatically generated by cvxgen. May be incorrect.
  variable x(34, 1);

  minimize((1/2)*quad_form(x, H) + f'*x);
  subject to
    x <= ub;
    x(1) >= lb(1);
    x(2) >= lb(2);
    x(3) >= lb(3);
    x(4) >= lb(4);
    x(5) >= lb(5);
    x(6) >= lb(6);
    x(7) >= lb(7);
    x(8) >= lb(8);
    x(9) >= lb(9);
    x(10) >= lb(10);
    x(11) >= lb(11);
    x(12) >= lb(12);
    x(13) >= lb(13);
    x(14) >= lb(14);
    x(15) >= lb(15);
    x(16) >= lb(16);
    x(17) >= lb(17);
    x(18) >= lb(18);
cvx_end
vars.x = x;
status.cvx_status = cvx_status;
% Provide a drop-in replacement for csolve.
status.optval = cvx_optval;
status.converged = strcmp(cvx_status, 'Solved');
